// -----------------------------------------------------------------------//
// Author : Zilong Fan
// Class  : ECE 6122 A
// Date   : 9/25/2023
// Version: 1
// Description :
	//Implement all the functions need in electric field class 
// -----------------------------------------------------------------------//

#include <iostream>
#include <iomanip>
#include <vector>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <atomic>
#include <sstream>      // std::istringstream
#include <string>       // std::string
#include <cmath>
#include "ECE_ElectricField.h"


void ECE_ElectricField::At(double a, double b, double c) 
{
	x_Pos = a;
	y_Pos = b;
	z_Pos = c;
}

void ECE_ElectricField::Zero()
{
	Ex = Ey = Ez = E = x_Pos = y_Pos = z_Pos = 0, 0;
	x = y = z = q = 0.0;
	exe_signal = 0;
}

double ECE_ElectricField::find_x()
{
	return x;
}

double ECE_ElectricField::find_y()
{
	return y;
}

double ECE_ElectricField::find_z()
{
	return z;
}

double ECE_ElectricField::find_Ex()
{
	return Ex;
}

double ECE_ElectricField::find_Ey()
{
	return Ey;
}

double ECE_ElectricField::find_Ez()
{
	return Ez;
}

void ECE_ElectricField::exe()
{
	if(exe_signal==0)
		exe_signal = 1;
	// test repeat calculation
	else
		std::cout << "wrong!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" << std::endl;
}

void ECE_ElectricField::computeFieldAt(double a, double b, double c)
{
	 x_Pos = a;
	 y_Pos = b;
	 z_Pos = c;

	 //std::cout << "Position:" << a << b << c << std::endl;
	 //std::cout << "charge_Position:" << x << "+" << y << "+" << z << std::endl;
	 //std::cout << "q: " << q << std::endl;

	 double r = sqrt((z_Pos - z) * (z_Pos - z) +
		 (x_Pos - x) * (x_Pos - x) + (y_Pos - y) * (y_Pos - y));
	 //std::cout << "r : " << r << std::endl;

	 Ex = k_micro * q / r / r * (x_Pos - x) / r;
	 //std::cout << "Ex : " << Ex << std::endl;
	 Ey = k_micro * q / r / r * (y_Pos - y) / r;;
	 //std::cout << "Ey : " << Ey << std::endl;
	 Ez = k_micro * q / r / r * (z_Pos - z) / r;;
	 //std::cout << "Ez : " << Ez << std::endl;

	///* calculate the electric field at (x,y,z) generated by one charge q located at (x,y,0)*/
	//// get the components of the vector 
	// double vector_X = x - this->x;
	// double vector_Y = y - this->y;
	// double vector_Z = z - this->z;

	// // calculate the magnitude suqare and the suqareroot of the vector
	// double vector_MagSquare = vector_X * vector_X + vector_Y * vector_Y + vector_Z * vector_Z;
	// double vector_Magsqrt = std::sqrt(vector_MagSquare);

	// // set constant value in the electric field equation
	// double coulomb_Constant = 9e9;

	// double ElectricField = (coulomb_Constant * this->q * 1e-6) / vector_MagSquare;

	// // get the components of the electrifc field 
	// this->Ex = (ElectricField * vector_X) / vector_Magsqrt;
	// this->Ey = (ElectricField * vector_Y) / vector_Magsqrt;
	// this->Ez = (ElectricField * vector_Z) / vector_Magsqrt;

}

void ECE_ElectricField::find_sum(ECE_ElectricField E_sub) 
{
	Ex += E_sub.find_Ex();
	Ey += E_sub.find_Ey();
	Ez += E_sub.find_Ez();
}

void ECE_ElectricField::getElectricField(double& Ex, double& Ey, double& Ez, double &E)
{
	std::cout << "The electric field at (" << x_Pos << ", " << y_Pos << ", " << z_Pos << ") in V/m is" << std::endl;
	std::cout << std::scientific;
	std::cout << "Ex = " << Ex << std::endl;
	std::cout << "Ey = " << Ey << std::endl;
	std::cout << "Ez = " << Ez << std::endl;
	E = sqrt(Ex * Ex + Ey * Ey + Ez * Ez);
	std::cout << "|E| = " << E << std::endl;
}

void ECE_ElectricField::getElectricField_self()
{
	std::cout << "The electric field at (" << x_Pos << ", " << y_Pos << ", " << z_Pos << ") in V/m is" << std::endl;
	std::cout << std::scientific;
	std::cout << std::setprecision(4) << "Ex = " << this->Ex << std::endl;
	std::cout << std::setprecision(4) << "Ey = " << this->Ey << std::endl;
	std::cout << std::setprecision(4) << "Ez = " << this->Ez << std::endl;
	E = sqrt(Ex * Ex + Ey * Ey + Ez * Ez);
	std::cout << std::setprecision(4) << "|E| = " << E << std::endl;
}

